# Generated by Django 5.2.7 on 2025-10-15 12:37

import django.db.models.deletion
import kew.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('prefix', models.CharField(blank=True, default='', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('services', models.ManyToManyField(blank=True, related_name='counters', to='kew.service')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=kew.models.localdate_default)),
                ('sequence', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('CALLING', 'Calling'), ('SERVED', 'Served'), ('SKIPPED', 'Skipped'), ('CANCELED', 'Canceled')], default='WAITING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('current_counter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='kew.counter')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='kew.service')),
            ],
        ),
        migrations.AddField(
            model_name='counter',
            name='current_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='kew.ticket'),
        ),
        migrations.CreateModel(
            name='CallEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('NEXT', 'Next'), ('PREV', 'Previous'), ('RECALL', 'Recall'), ('DONE', 'Done'), ('SKIP', 'Skip')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='kew.counter')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='kew.ticket')),
            ],
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'service', 'date'], name='kew_ticket_status_39fe83_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at'], name='kew_ticket_created_e0068c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('service', 'date', 'sequence')},
        ),
    ]
