# Generated by Django 5.2.7 on 2025-11-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kew', '0002_callevent_user_counter_assigned_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon_class',
            field=models.CharField(default='fas fa-cog', max_length=50),
        ),
    ]
