# Generated by Django 5.2.7 on 2025-12-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kew', '0003_service_icon_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('CALLING', 'Calling'), ('SERVED', 'Served'), ('SKIPPED', 'Skipped'), ('CANCELED', 'Canceled'), ('TRANSFERRED', 'Transferred')], default='WAITING', max_length=15),
        ),
    ]
